# If you find yourself editing these this file very often, consider using
# Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# {{ site.myvariable }}

# Basic
name:               "Olivia Rose Graham"
description: > # this means to ignore newlines until "baseurl:"
  Olivia Graham: Freelance/contract full-stack web developer
  for hire.
headline: >
  I'm Olivia, a full-stack web developer with over 5 years development experience
  currently working in London, UK.
author:
  name:             Olivia Graham
  twitter:          olivzz
  github:           livgrhm
  linkedin:         oliviagraham
  email:            livgrhm@gmail.com
  # facebook:         your-id
  # medium:           your-id
  # tumblr:           your-id

resumeurl:          "https://www.kickresume.com/cv/livgrhm/"

# Google-analytics
google-analytics:
  id:               "UA-88087634-1"

# Google-maps
google-maps:
  api-key:          "AIzaSyBjkBdpW_SZDPdorgPWCXxeYFYBu_sKYNg"

# Disqus
disqus:
  id:               "disqus_qNXesJ0P0V"

# URL
#production
#url:                "http://livgrhm.com" # the base hostname & protocol for your site
#development
url:               "localhost:4000"
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/London
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           6
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "Skills"
    url:            "#skills"
  - name:           "Hire Me"
    url:            "#hireme"
  - name:           "Portfolio"
    url:            "#portfolio"
  - name:           "Blog"
    # url:            "/blog"
    url:            "#blog"
  - name:           "Instagram"
    url:            "#instagram"
  - name:           "Contact"
    url:            "#contact"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

# exclude:            [vendor]
