# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: "minima"

# Basic
name:               "Livgrhm.com"
description: > # this means to ignore newlines until "baseurl:"
  Olivia Graham: Freelance/contract full-stack web developer
  for hire.

author:
  name:             Olivia Graham
  # facebook:         your-id
  twitter:          livgrhm
  github:           livgrhm
  linkedin:         oliviagraham
  # medium:           your-id
  # tumblr:           your-id
  email:            livgrhm@gmail.com

# Google-analytics
# google-analytics:
#   id:               ""

# Disqus
# disqus:
#   id:               "your-id"

# URL
#url:                "http://livgrhm.com" # the base hostname & protocol for your site
url:               "localhost:4000"
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/London
permalink:          /:year-:month-:day/:title/

# Pagination
# paginate:           5
# paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            ""

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
#   - jekyll-paginate

# exclude:            [vendor]
